language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - iojs

script: node_modules/karma/bin/karma start test/unit/karma.conf.js --single-run

# Google Chrome
#
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
#
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: 'npm run coveralls'
